### ISSUE TITLE
FEAT :  Homepage Design and Development

### ISSUE THREAD

**Issue by TenzDelek** [TenzDelek/DearDiary#1]
# Task
design and develop a homepage for the DearDiary 
the Homepage should be consider following criteria:
1. default dark mode True
2. modern minimalistic look ( can use shadcn component)
3. refer this 
<img width="1280" alt="image" src="https://github.com/user-attachments/assets/932ad9e9-e7bf-4b92-aa73-3f96bd47e92e">

**Comment by Abhi0049k** [comment]
@TenzDelek, please assign me this issue

**Comment by TenzDelek** [comment]
@Abhi0049k  go ahead
