### ISSUE TITLE
UI issue: I found issues in the footer!

### ISSUE THREAD

**Issue by deepanshu-prajapati01** [TenzDelek/DearDiary#101]
### The bug/issue i encounter is that there are 2 routes who have **2 different footers.**

![image](https://github.com/user-attachments/assets/7c6a72e9-c965-47ec-9165-150aa5745ba2)

**In this image we can clearly see there are 2 footers.** 
### Similarly, Footer with this text '© 2024 Daily Quotes. All rights reserved.' can be seen again at '/about' route,

![image](https://github.com/user-attachments/assets/8b750633-ef9c-4d9e-96dc-a77261a28217)

I want to resolve this issue, by combining them to one main footer.js file under the Components directory!

_As a beginner, i would love if i can get more details which i can add in the footer!_

**Comment by TenzDelek** [comment]
one issue is working on that
