### ISSUE TITLE
toggle bottom CTA section based on the user login

### ISSUE THREAD

**Issue by vamsi4845** [TenzDelek/DearDiary#102]
### Is your proposal related to a problem?

The  bottom CTA section content is a bit misleading it shows signup now even after the user is logged in
![image](https://github.com/user-attachments/assets/15f571c5-8de8-4b2c-9a61-a8b02d162664)

(Write your answer here.)

### Describe the solution you'd like

Something like this where the user gets redirected to /notes on clicking the CTA (if the user is logged in)
![image](https://github.com/user-attachments/assets/b5fe4db5-5247-4db1-af2e-cce582fe979f)

### Additional context

I would like to work on this

**Comment by TenzDelek** [comment]
one issue is working on that #99
