### ISSUE TITLE
Hover effect

### ISSUE THREAD

**Issue by Monu2114** [TenzDelek/DearDiary#107]
### Is your proposal related to a problem?

The front page's UI can be enhanced by introducing hover effects around the features 

### Describe the solution you'd like

![image](https://github.com/user-attachments/assets/a6ec139b-e487-4725-a92b-d8505fddc15a)
i want to introduce hover effects around the boxes to ensure user has a better ui ux experience
(Describe your proposed solution here.)

### Additional context

Pls add labels gssoc-extd,hacktoberfest-accepted and level 2

(Write your answer here.)

### Requirement/Document

(Share it here.)

**Comment by TenzDelek** [comment]
go ahead
