### ISSUE TITLE
Images in the frontend to make ui better

### ISSUE THREAD

**Issue by Monu2114** [TenzDelek/DearDiary#108]
### Is your proposal related to a problem?

The site looks pretty blank. Including image can greatly improve the appearance and increase user experience

(Write your answer here.)

### Describe the solution you'd like

![image](https://github.com/user-attachments/assets/8be8d2c5-05bb-469a-836b-43ff950b1be3)
the site seems so blank and unattractive. Including one or two images related to diary can enhance the appearance
(Describe your proposed solution here.)

### Describe alternatives you've considered

pls assign gssoc24-extd, level1, hacktoberfest-accepted

(Write your answer here.)

### Additional context

(Write your answer here.)

### Requirement/Document

(Share it here.)

**Comment by TenzDelek** [comment]
this is the theme we are going with so closing the issue as not planned
