### ISSUE TITLE
Adding Diary page link in the Navbar.

### ISSUE THREAD

**Issue by Abhi0049k** [TenzDelek/DearDiary#109]
### Description
Right now there is no button or link redirecting the users to the diary page where they can create a diary or edit there previous diary.

### Describe the solution you'd like
Simply Add a Link in the navbar to the diary page where users can create and edit their diaries.

### Screenshot
![image](https://github.com/user-attachments/assets/844eadde-c01a-4a0b-b757-b6589571e1a1)

**Comment by TenzDelek** [comment]
go ahead
