### ISSUE TITLE
Lack of Visual Appeal and User-Friendliness in Current UI Design in the background of landing Page

### ISSUE THREAD

**Issue by kekubhai** [TenzDelek/DearDiary#110]
### Is your proposal related to a problem?

Yes, my proposal is related to a problem. The current user interface (UI) design is visually unappealing and user-hostile, making it difficult for users to navigate and interact with the application effectively. 

### Describe the solution you'd like

To address this issue, I propose implementing a more visually appealing and user-friendly UI design. This would involve introducing a color palette, ensuring sufficient contrast, leveraging visual hierarchy, and conducting usability testing to gather feedback and make necessary adjustments. 

### Describe alternatives you've considered

While I have not considered any specific alternatives, I believe that maintaining the current UI design would continue to negatively impact user experience and potentially lead to user dissatisfaction. 

### Additional context

The current UI design primarily consists of a black background, which creates a stark and potentially difficult-to-read interface. This lack of visual contrast and variety makes it challenging for users to navigate and interact with the application effectively.

**Comment by TenzDelek** [comment]
we did recieved many issue regarding the current UI. but to be honest I love minimal look of the current one. but if you think it can be further improve , share me a mock design or a design inspo.

**Comment by kekubhai** [comment]
Yes a dev I understand your perspective, but everyone will first have an eye on the deisgn and structure of the websites,That's where many websites stand out. The rest of the designs are all good , I just want to add a background with the black colour to make it look more appealing. I have selected some of the UI designs just goo great with your websites, Check Them if you like



.
![Screenshot 2024-10-14 213136](https://github.com/user-attachments/assets/4a8b3000-9493-405d-b8db-6c104e8dfdfc)
![Screenshot 2024-10-14 213214](https://github.com/user-attachments/assets/2e522e65-8701-4670-8c45-946646680ba0)
![Screenshot 2024-10-14 213239](https://github.com/user-attachments/assets/a82cf190-2516-4918-ad8c-24ae52da38b1)
![Screenshot 2024-10-14 213356](https://github.com/user-attachments/assets/1a30b221-53a9-4a88-8e86-10bd8b840d48)

![Screenshot 2024-10-14 213436](https://github.com/user-attachments/assets/d47476b5-1bc7-4c6e-855e-2751d3ee7716)
![Screenshot 2024-10-14 213449](https://github.com/user-attachments/assets/f65c5b69-4023-40c4-b678-58372e37c451)



Each of these are animated and will add a great UI/UX to the viewer at once. It fits great with your websites too. Do tell me if you like any of the ones given above so that i can start implementing them . Thank You
