### ISSUE TITLE
404 Error on "Get Started" Button Redirect

### ISSUE THREAD

**Issue by amitb0ra** [TenzDelek/DearDiary#113]
## Issue Summary

The "Get Started" button currently leads to a 404 error page when clicked. This occurs after a user has signed up successfully and is redirected to the "/get-started" route, which does not exist. This issue can lead to confusion for users, as they expect to be guided through an onboarding process after signing up. 

### Steps to Reproduce

1. Navigate to the application homepage.
2. Click the "Get Started" button, user is met with a 404 error page.
3. If not authenticated, sign up using the provided sign-up form.
4. After successful sign-up, observe that the application redirects to the "/get-started" page.
5. The user is met with a 404 error page.

![image](https://github.com/user-attachments/assets/158d26bd-2f5c-4643-a014-8fb33d7db870)

### Expected Results

Could you please advise on how to proceed with this issue? Should a new "Get Started" page be created, or should users be redirected to another page like "/notes", or instead "Get Started" in the button, it should show "Go to Diary"? 

Additionally, please assign this issue under **gssoc-ext** and **hacktoberfest**.

**Comment by TenzDelek** [comment]
navigate it to notes
