### ISSUE TITLE
Proposal for Improved Footer Design

### ISSUE THREAD

**Issue by amitb0ra** [TenzDelek/DearDiary#114]
## Issue Summary

The current footer contains only a GitHub link and a site link. This minimal design lacks essential information and navigational options that could enhance user experience and engagement. 

![image](https://github.com/user-attachments/assets/70193f17-37e1-4e20-9764-51eae465aaeb)

### Suggested Improvements

1. **Add Additional Links**: Include links to important sections of the application, such as:
   - About Us
   - Contact Us
   - Privacy Policy
   - Terms of Service
   - Help/FAQ

2. **Social Media Links**: If applicable, include links to social media accounts to allow users to connect with the project team and stay updated.

3. **Copyright Information**: Add copyright information to indicate ownership and protect the project legally.

4. **Design Considerations**: Ensure the footer design is visually appealing and consistent with the overall theme of the application.

### Technical Details

- **Current Footer Layout**: As shown in the attached image, the footer currently consists of just the GitHub and site links.
- **Proposed Changes**: A mockup of the new footer design can be created to illustrate how the additional elements would be arranged.

### Request for Maintainer

Would it be possible to implement these changes to enhance the footer? If so, please let me know if you would like me to create a mockup or assist in implementing this improvement. 

Additionally, please assign this issue to me under **gssoc-ext** and **hacktoberfest**.

**Comment by TenzDelek** [comment]
duplicate issue so closing this
