### ISSUE TITLE
Notes Page Lacks Core Functionality

### ISSUE THREAD

**Issue by amitb0ra** [TenzDelek/DearDiary#116]
## Issue Summary

The "Notes" page in the DearDiary project currently does not allow users to create or manage notes. As this is a core functionality of the application, the lack of a working notes feature significantly affects user experience.

![image](https://github.com/user-attachments/assets/29e83168-674a-4b8c-be08-e29073413c41)

### Steps to Reproduce

1. Navigate to the "Notes" page.
2. Attempt to create a new note or interact with the existing UI (if any).
3. Observe that there are no options to add, edit, or delete notes.

### Actual Results

- The "Notes" page does not provide any way to create or manage notes, leaving the user unable to utilize a core feature of the application.

### Expected Results

- The "Notes" page should have functionality that allows users to:
  - Create a new note.
  - View and manage existing notes.
  - Edit and delete notes.
  - Optionally, categorize or tag notes for better organization.

### Technical Details

- **Current Implementation**: The "Notes" page appears to lack essential functionality.
- **Proposed Changes**: Introduce UI and back-end functionality to handle note creation and management, ensuring it aligns with the core objective of the application.

### Request for Maintainer

Could you please prioritize adding note-taking functionality to the "Notes" page? This is essential for users to interact meaningfully with the DearDiary application. 

Additionally, please assign this issue to me under **gssoc-ext** and **hacktoberfest**.

**Comment by TenzDelek** [comment]
go ahead. its priority for the web
