### ISSUE TITLE
[Fix] Form Fields Not Clearing After Submission

### ISSUE THREAD

**Issue by Abhi0049k** [TenzDelek/DearDiary#117]
### Issue Summary
After submitting the data through the form, the expected behavior is that the form fields should be reset and cleared. However, the current implementation retains the previously entered values even after a successful submission. This leads to confusion for users, as they may think the form has not been submitted or that the data needs to be resubmitted.

### Steps to Reproduce
1. Visit: `/diary`
2. Try to submit a diary entry.
3. After loading is complete, observe that the form fields retain the previous values.

### Actual Results
After loading is complete, the form still retains the previous values.

### Expected Results
After loading is complete, the form fields should be cleared.

### Screenshot
![image](https://github.com/user-attachments/assets/6e5c5f35-c235-4350-8a1b-3886a434c6b8)

**Comment by Abhi0049k** [comment]
@TenzDelek please assign this issue to me?

**Comment by Abhi0049k** [comment]
@TenzDelek , can you open some issues since you are the most familiar with the project?

**Comment by Abhi0049k** [comment]
@TenzDelek , could you also add a brief description of what this project is about? Nowhere is it mentioned what the project is or what it does.

**Comment by TenzDelek** [comment]
go ahead, with the issue, currently a bit busy
