### ISSUE TITLE
Navbar Not Fixed: Scrolls with Page Content

### ISSUE THREAD

**Issue by sps234** [TenzDelek/DearDiary#118]
Description:
I have noticed that the navbar component in the project is not fixed and scrolls along with the page. This behaviour is not expected, as I believe the navbar should remain fixed at the top of the viewport during scrolling.

Steps to reproduce:
1. Navigate to home page within the application.
2. Scroll down the page.
3. Observe that the Navbar moves with the scroll instead of staying fixed at the top.

Expected behaviour: The navbar should remain fixed at the top of the viewport, allowing easy access to navigation links without having to scroll back up.

Actual behaviour: The navbar scrolls with the rest of the page content, which can lead to a less user-friendly experience.

"Please assign this issue to me so that I can work on it."

**Comment by TenzDelek** [comment]
go ahead
