### ISSUE TITLE
Navbar Stickiness and Mobile Experience Issues

### ISSUE THREAD

**Issue by deepanshu-prajapati01** [TenzDelek/DearDiary#120]
### **Issue Summary**

The current navbar implementation is not providing an optimal user experience, particularly on mobile devices.  Also, the mobile navbar lacks animations and appears abrupt when expanded or collapsed, leading to a less engaging interaction. Additionally the navbar does not remain fixed at the top of the screen, requiring users to scroll back to the top to access navigation links. This thing create more problem for the users on mobile devices.

### **Steps to Reproduce**

1. Access the application on a mobile device.
2. Navigate to any page within the application.
3. Scroll down the page.
4. Attempt to access a navigation link from the navbar.

### **Actual Results**

The navbar does not remain fixed at the top of the screen, forcing users to scroll back to the top to access navigation links. When expanding or collapsing the mobile navbar, there are no animations or transitions, resulting in a jarring and less user-friendly experience.

### **Expected Results**

The navbar should remain fixed at the top of the screen, providing easy access to navigation links regardless of the user's scroll position. Expanding and collapsing the mobile navbar should be accompanied by smooth animations, creating a more visually appealing and intuitive interaction.

###**Additional context**

_Please assign this issue to me and add these labels -> gssoc-extd,hacktoberfest-accepted and level 2_

### **Navbar not fixed issue**
![image](https://github.com/user-attachments/assets/57762324-ed4e-46b8-ad40-49d14e0ddae7)

### **Poor mobile experience**
![image](https://github.com/user-attachments/assets/d19053b9-e674-46da-ad90-f8bd969a3a71)

**Comment by TenzDelek** [comment]
go ahead

**Comment by deepanshu-prajapati01** [comment]
Hi @TenzDelek, I am just curious because it has been a while now since I have raised a PR according the the issue, but I am not getting any kind of response. I am newbie and this is the first time I am contributing to any open source project. Can you guide me like what I did wrong due to which my PR has not been merged and neither I got any response in my PR.

Previously, I fixed 2 issues, one was about the Navbar stickness to the top and the other is related to responsive and better navbar.

But unfortunately, the PR raised by another person about fixing the 1st issue (Sticky navbar at the top) got merged but not mine.
To resolve conflicts in merging, it takes me to fix the code and i raised another PR request but still I haven't got anything response. Can you tell me in brief what's the issue in my PR.

It will help me to understand motivate me to look forward on more issues.
