### ISSUE TITLE
Adding the contributors page to mention all the awersome people who have contributed to the website.

### ISSUE THREAD

**Issue by tarunkumar2005** [TenzDelek/DearDiary#123]
Adding the contributors page to mention all the awersome people who have contributed to the website.

@TenzDelek Assign this to me under gssoc 2024 ext and hacktoberfest i will work on this issue.

**Comment by tarunkumar2005** [comment]
On the website i am suggesting it will be better on website for networking and all

**Comment by TenzDelek** [comment]
go ahead
