### ISSUE TITLE
Adding Copy Confirmation and Loading State

### ISSUE THREAD

**Issue by shamvrueth** [TenzDelek/DearDiary#150]
### Is your proposal related to a problem?

I'm frustrated when the original site does not provide feedback upon clicking the "Copy" button or when a new quote is requested using the "New Quote" button. Users are left without confirmation that the actions they triggered have occurred, which reduces the clarity and usability of the site.

### Describe the solution you'd like

I have implemented a solution where:

Upon clicking the "Copy" button, a message is displayed to confirm that the quote was copied.
When the "New Quote" button is clicked, a loading indicator is shown before displaying the new quote.
These changes enhance user experience by providing clear feedback.

### Additional context

I have attached video recordings demonstrating the modified functionality compared to the original site. This shows the added message for copying and the loading indicator when a new quote is requested.

### Requirement/Document

https://github.com/user-attachments/assets/39b9186c-f120-4a99-b1ae-2bc218c45e94

**Comment by TenzDelek** [comment]
go ahead

**Comment by Balamurugan-cyber** [comment]
could you please assign this issue

**Comment by shamvrueth** [comment]
I've created a new pull request
