### ISSUE TITLE
To change the ReviewModal

### ISSUE THREAD

**Issue by inkerton** [TenzDelek/DearDiary#155]
### Is your proposal related to a problem?

No clear marging and if this can be made rectangular I would look more appealing. also on submit the thankyou toast is not in between the page but between the section these should be atleast as seperation between the two . If the toast is in between then the background text should not be visible atleast. It confused me very much at first glance

![image](https://github.com/user-attachments/assets/bd815232-a8f2-4fe6-983e-ad87b37933e0)
![image](https://github.com/user-attachments/assets/57a60526-4d6f-46d3-bb3c-7861588f5d0f)

### Describe the solution you'd like

![image](https://github.com/user-attachments/assets/f7e8b8ac-84b9-4ede-b29a-da55f4e54c69)

**Comment by inkerton** [comment]
![image](https://github.com/user-attachments/assets/2daec89a-53e8-438d-83b4-0d4442f88dfc)

Now this looks better

**Comment by Aditya-PS-05** [comment]
Can you assign me this issue?

**Comment by inkerton** [comment]
It hasn't been 3 days since the task was assigned I am working on it.
