### ISSUE TITLE
Add Dark/Light Mode Toggle Button

### ISSUE THREAD

**Issue by Priyanshu282003** [TenzDelek/DearDiary#157]
Description:
Currently, the application lacks an option to switch between dark and light themes. Implementing a toggle button for dark and light modes would enhance user experience by allowing users to choose their preferred theme. This feature is especially beneficial for accessibility and can improve usability in various lighting environments.

Expected Behavior
A toggle button is available on the main interface to switch between dark and light themes.
The selected theme should be retained even after a page refresh or on revisiting the site.
Additional Context
This feature would allow users to personalize their experience and may reduce eye strain for users working in low-light conditions.

**Comment by vamsi4845** [comment]
@TenzDelek  Can you assign this to me I've already built this functionality

https://github.com/user-attachments/assets/7846221d-29e7-4371-ad0f-9f16a3785eeb
