### ISSUE TITLE
remove the hover blue line

### ISSUE THREAD

**Issue by TenzDelek** [TenzDelek/DearDiary#159]
<img width="899" alt="image" src="https://github.com/user-attachments/assets/173ea56b-d28f-4081-80df-34bf9a8b947a">

**Comment by Aditya-PS-05** [comment]
Can you assign me this issue?

**Comment by TenzDelek** [comment]
@vamsi4845  raise a pr, will merge

**Comment by vamsi4845** [comment]
> @vamsi4845 raise a pr, will merge

Done
