### ISSUE TITLE
 Feature Request: Quote of the Day Customization

### ISSUE THREAD

**Issue by sezallagwal** [TenzDelek/DearDiary#162]
#### Description
Allow users to personalize the "Quote of the Day" feature by selecting from different categories (e.g., motivational, reflective). This feature will give users a tailored and inspiring journaling experience.

#### Proposed Features
- **Category Selection:** Users can select a theme for their daily quotes, like "motivational," "reflective," or "gratitude."
- **Custom Quotes:** Allow users to add their own favorite quotes to display in the "Quote of the Day" section.

#### Tasks
1. **UI Update:** Create an interface for users to select quote categories or add custom quotes.
2. **Quote Database:** Implement a backend system to store and categorize quotes.
3. **Daily Display:** Ensure the selected or custom quote appears daily on the user's dashboard.

#### Benefits
- Provides a personalized, motivating experience for users.
- Increases user engagement by letting them see quotes that resonate with them.

---

**Please assign this issue to GSSoC'24 ext and Hacktoberfest labels.**

**Comment by TenzDelek** [comment]
go ahead
