### ISSUE TITLE
FEATURE: Automated Greeting Workflow

### ISSUE THREAD

**Issue by harish08102004** [TenzDelek/DearDiary#18]
I propose to create a Github workflow named "Greetings". This workflow will automatically greet users who create new issues or pull requests in this repository. The Greetings will look like "Hi there! Thanks for opening this issue. We appreciate your contribution to this open - source project. We aim to respond or assign your issue as soon as possible .

Hey @TenzDelek can you assign task.

**Comment by TenzDelek** [comment]
looks promising ! sure go ahead cc @harish08102004

**Comment by harish08102004** [comment]
Hey @TenzDelek I have raised the PR please check it and merge.

**Comment by TenzDelek** [comment]
will look into it ! , do star the repo !! it helps in visibility
