### ISSUE TITLE
[Enhancement] Navbar enhancement

### ISSUE THREAD

**Issue by LegendCK** [TenzDelek/DearDiary#184]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Navbar color is bit darker than it's background when we increase the brightness of screen. 

### Actual Results

![image](https://github.com/user-attachments/assets/483564dd-1e4a-46e7-8de4-896f78f611db)

### Expected Results

![image](https://github.com/user-attachments/assets/d5443366-b242-4a65-8e91-82b8e25558c6)

Also if not we can enhance the navbar by having the color to be white with rounded corners as it will enhance the UI/UX. And same can be applied to SignIn button.

**Comment by LegendCK** [comment]
@TenzDelek Alr! Should I change the color of navbar and signin button or just update the navbar color similar to background?

**Comment by LegendCK** [comment]
Something like this
![image](https://github.com/user-attachments/assets/b4e9f850-6d5f-4691-b023-afc4b8e36fd0)
or I'll keep this one
![image](https://github.com/user-attachments/assets/9d5d81ae-d88d-4233-9a4c-ea2e65e70299)

**Comment by LegendCK** [comment]
@TenzDelek Can please suggest me which should I do?

**Comment by Abhi0049k** [comment]
@TenzDelek, Can I work on this issue?

**Comment by LegendCK** [comment]
@TenzDelek Hey, Can you please help me with selection or fix?

> Something like this ![image](https://private-user-images.githubusercontent.com/134909263/380836108-b4e9f850-6d5f-4691-b023-afc4b8e36fd0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5MDA4ODQsIm5iZiI6MTczMDkwMDU4NCwicGF0aCI6Ii8xMzQ5MDkyNjMvMzgwODM2MTA4LWI0ZTlmODUwLTZkNWYtNDY5MS1iMDIzLWFmYzRiOGUzNmZkMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNlQxMzQzMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YjViNWM5Mjk2OTQ1ODdhYzZmNDNmZTZjMDExZGQwZjBiNWQxZTEzMjg4NjYzNDE1ZWZmNTlmYjM0ZTExNmIzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.zgBi5hlsflenWaan20rhx6ebsNiL2KZ0e51N-yf6TAI) or I'll keep this one ![image](https://private-user-images.githubusercontent.com/134909263/380836361-9d5d81ae-d88d-4233-9a4c-ea2e65e70299.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5MDA4ODQsIm5iZiI6MTczMDkwMDU4NCwicGF0aCI6Ii8xMzQ5MDkyNjMvMzgwODM2MzYxLTlkNWQ4MWFlLWQ4OGQtNDIzMy05YTRjLWVhMmU2NWU3MDI5OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNlQxMzQzMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03OWU1Y2EzNjVmMmFhZTMyYTQ2NGVmNTMzNzY0YzlkMzc2N2Y0MGY1M2NmOGUwYmQ2N2JiM2FiOWYxNDJiODgwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.9Lli99Mx8kITMjotvF12VTxJzICn6my7H8ZKQrWYUlg)

**Comment by TenzDelek** [comment]
@LegendCK  just go with the expected result that you showed in the issue (removing the black bg)
