### ISSUE TITLE
Sign-In Functionality Not Working for Signup Form

### ISSUE THREAD

**Issue by TanyaaSrivastava** [TenzDelek/DearDiary#187]
1. The current sign-in function is not operating as expected, impacting both the login and signup forms. When users attempt to log in or create a new account, the forms do not successfully authenticate or process the input, preventing access to the account dashboard or user-specific features.
2. This issue may stem from a backend authentication problem, incorrect API integration, or validation errors on the frontend forms. Investigating the login and signup flow, including error handling and form submission processes, will help identify the root cause to restore full sign-in functionality.

**Comment by TenzDelek** [comment]
we are using clerk for the auth , i dont see any problem there, can you share a screen recording for more clarification
