### ISSUE TITLE
Proposal to add a contributing.md

### ISSUE THREAD

**Issue by nishakp3005** [TenzDelek/DearDiary#28]
# Proposal to Add a Contributing.md to Improve the Contribution Experience

---

### Is your proposal related to a problem?
Right now, we don’t have any specific guidelines for contributors. This might make it tricky for new contributors to understand our best practices, code style, and submission process, potentially leading to inconsistencies in contributions.

### Describe the solution you'd like
I propose we create a `Contributing.md` file to help guide anyone who wants to contribute. This document could include:
- Instructions on setting up the development environment
- Clear code style guidelines
- Conventions for commit messages
- Guidelines for submitting pull requests
- A preferred branching strategy for new features or bug fixes
- An overview of our review and approval process
- Information on how contributions will be licensed

Having these details in one place will make it easier for everyone to contribute effectively, while helping us maintain consistency and quality.

### Describe alternatives you've considered
We could add a shorter guide to the README, but a dedicated `Contributing.md` file would allow us to go into more detail without overloading the main README.

### Additional context
Many open-source projects include a `Contributing.md` file as a best practice to make it easier for both new and experienced contributors to get involved. Adding one here would help us improve collaboration and make contributing to our project a smoother experience.

### Requirement/Document
To support this proposal, I’m happy to start by drafting a `Contributing.md` based on standard open-source contribution practices. We can then tailor it to fit our project’s specific needs.

@TenzDelek kindly assign this issue to me

**Comment by TenzDelek** [comment]
also do star the repo, it help in visibility cc @nishakp3005
