### ISSUE TITLE
Clerk redirection page revamp

### ISSUE THREAD

**Issue by TenzDelek** [TenzDelek/DearDiary#3]
after the clerk implementation is done, make a custom route for the clerk and design it according to the homepage theme
ref :
<img width="1280" alt="image" src="https://github.com/user-attachments/assets/ada4751d-dd69-427e-bc43-e31afe3e65c4">

**Comment by ananyakaligal** [comment]
could you please assign me this

**Comment by TenzDelek** [comment]
go ahead !

**Comment by Sourabh782** [comment]
@ananyakaligal you working on this issue? if not @TenzDelek can i work on it?

**Comment by TenzDelek** [comment]
assigning the issue to @Sourabh782

**Comment by Sourabh782** [comment]
working on it

**Comment by Abhi0049k** [comment]
@TenzDelek, Can you assign this issue to me?

**Comment by Abhi0049k** [comment]
@TenzDelek, can you assign this issue to me?

**Comment by TenzDelek** [comment]
go ahead

**Comment by Abhi0049k** [comment]
Hi @TenzDelek, I have raised a pull request for this issue
