### ISSUE TITLE
Fix : Convert the .png to .webpg for all file in public

### ISSUE THREAD

**Issue by TenzDelek** [TenzDelek/DearDiary#30]
refer title 
you can do that in https://squoosh.app/

**Comment by dheerajsingh01** [comment]
hey @TenzDelek  i can do this task if you assign it to me.

**Comment by TenzDelek** [comment]
go ahead @dheerajsingh01 
also do star the repo , it helps in visibility

**Comment by dheerajsingh01** [comment]
hey @TenzDelek can you check my PR and reply if any issue.

**Comment by mashazyu** [comment]
@TenzDelek 

Is this issue available? If yes, I could give it a try.

**Comment by TenzDelek** [comment]
yes go ahead
