### ISSUE TITLE
Feat : dark mode and light mode

### ISSUE THREAD

**Issue by TenzDelek** [TenzDelek/DearDiary#32]
should be functional across all page and support tailwind
use contextapi or redux or any other state management

**Comment by Sourabh782** [comment]
Hello @TenzDelek, i wanted to work on this issue, i have implemented same previously during gssoc'24, OnlineBookSales project. so i have prev exp in this

**Comment by TenzDelek** [comment]
go ahead @Sourabh782 
also do star the repo, it helps in visibility

**Comment by Sourabh782** [comment]
Thanks @TenzDelek, will complete till sun, and yup starred

**Comment by Sourabh782** [comment]
hey @TenzDelek,  i have implemented it like functionality part, should i add working part also?

**Comment by TenzDelek** [comment]
We have Lucide react in our package so it shouldn't be a problem, I didn't get the first part , can you come at me again with that?

**Comment by Sourabh782** [comment]
@TenzDelek  ys i saw lucide, sorry for that part

Actually i implemented dark mode and toggel dark mode, like context and wrapped the application inside context, so dark mode is working now. but you cant see the changes as its not added to pages ( the dark: class)

**Comment by Sourabh782** [comment]
@TenzDelek  like this:

https://github.com/user-attachments/assets/dfd973d7-c9e6-4df7-be39-d7f88ed33a29

so its working, but dark: classes are not added, so can i push this as it is?

**Comment by TenzDelek** [comment]
Lgtm , you can make a pr

**Comment by Sourabh782** [comment]
sure

**Comment by Sourabh782** [comment]
@TenzDelek kindly check it
