### ISSUE TITLE
Feat: create guestbook

### ISSUE THREAD

**Issue by TenzDelek** [TenzDelek/DearDiary#37]
take inspiration from this site : https://www.knlrvr.dev/guestbook
https://bejamas.io/hub/guides/how-to-create-a-guestbook

**Comment by mchen610** [comment]
Hello, do we want to use vercel and the serverless postgres like in the guide?

**Comment by mchen610** [comment]
Please assign this to me, I completed it and will make the PR in a minute

**Comment by TenzDelek** [comment]
will look into the pr soon cc @mchen610
