### ISSUE TITLE
Feat : Create a user guide for beginner contributor

### ISSUE THREAD

**Issue by TenzDelek** [TenzDelek/DearDiary#4]
mostly update the readme to guide the new user 
it should contain
1. project setup for nextjs and clerk
2. basic guideline

**Comment by kartikey369-ind** [comment]
Hi @TenzDelek 

I hope you’re doing well. I would like to take the initiative to create a user guide for beginner contributors to our project. This guide will help new contributors understand the project setup, especially for Next.js and Clerk, along with basic contribution guidelines.

Could you please assign this task to me?

**Comment by TenzDelek** [comment]
hey @kartikey369-ind , wait till tomorrow as it is the official date. 
will assign you once the event is commence

**Comment by kartikey369-ind** [comment]
Ok sure

**Comment by TenzDelek** [comment]
@kartikey369-ind  assigned

**Comment by kartikey369-ind** [comment]
sone please check https://github.com/TenzDelek/DearDiary/pull/11
