### ISSUE TITLE
DOC : Supabase and prisma setup docs

### ISSUE THREAD

**Issue by TenzDelek** [TenzDelek/DearDiary#42]
write this content from the screenshot in the readme.md to help new contributors
![image](https://github.com/user-attachments/assets/887dc97f-805b-4e44-8b12-3e68841ef5e3)

**Comment by DeeptejD** [comment]
Can you assign this to me?

**Comment by TenzDelek** [comment]
sure go ahead  @DeeptejD 
also do star the repo, it helps in visibility

**Comment by DeeptejD** [comment]
I've raised a PR can you check it out and merge it?
