### ISSUE TITLE
Add Missing Meta Tags for SEO Enhancement

### ISSUE THREAD

**Issue by myselfshivams** [TenzDelek/DearDiary#45]
The current project lacks essential meta tags that are crucial for search engine optimization (SEO). To improve the visibility and ranking of the website on search engines, we need to add the following missing meta tags:

- Title tags
- Description tags
- Keywords tags
- Open Graph tags for social media sharing
- Robots meta tag

@TenzDelek  Please assign this issue to me (@myselfshivams).

Labels:
- GSSoC
- Hacktoberfest

**Comment by TenzDelek** [comment]
love the idea, go ahead @myselfshivams 
also do star the repo
