### ISSUE TITLE
incorrect folder structure for next.js

### ISSUE THREAD

**Issue by jaison-jai-john** [TenzDelek/DearDiary#48]
### Issue Summary

according to the [next.js documentary](https://nextjs.org/docs/getting-started/project-structure) the project structure should be as follows. 

![image](https://github.com/user-attachments/assets/afff4a1c-ab3f-4b0d-b709-2525974861a5)

yet we have the app folder nested inside src like a react project. the app folder and sec folders are top level folders and do not share a parent child relationship in a next.js project

### Steps to Reproduce

open the file directory

### Actual Results

- NA

### Expected Results

- NA

### Technical details

- might lead to bugs and conflicts as the project grows over time if not resolved

**Comment by TenzDelek** [comment]
@jaison-jai-john sorry but I don't see any problem here. The build was done with next latest package. Closing this issue as for now.
