### ISSUE TITLE
Feat : Navbar 

### ISSUE THREAD

**Issue by TenzDelek** [TenzDelek/DearDiary#5]
should be reponsive and modern ( can make use of shadcn)
should contain a logo (will provide) at left and at rightside a button (clerk) and routes

**Comment by nithinrvs** [comment]
Hello @TenzDelek I would like to work on this, can you please specify what are all the pages/routes that'll be present and assign the issue to me.

**Comment by TenzDelek** [comment]
sure , currently make three route : home , notes and Daily quote.
cc @nithinrvs 
also do star the repo 😄
