### ISSUE TITLE
Creating About page

### ISSUE THREAD

**Issue by Hh440** [TenzDelek/DearDiary#52]
creating the About page which gives the user an infomation about feature that the website provide and also the future insight.

- Mission: A brief description of what our website aims to achieve.
- Key Features: A summary of the main functionalities we offer.
- User Benefits: How our platform helps and supports users.
- Technologies: Highlighting the technology stack we use.
- Security & Privacy: Information on how we ensure user data is safe.
- Future Insights: A glimpse of upcoming features and plans for the platform.

![Screenshot from 2024-10-06 18-34-53](https://github.com/user-attachments/assets/dd3cba52-6924-4c2c-b71a-7d2038f94824)

**Comment by MohitGoyal09** [comment]
Pls assign me this task under hackotober fest tags.

**Comment by TenzDelek** [comment]
@Hh440  are you going to work on this or @MohitGoyal09 ?
the priority will be given to @Hh440  as he suggested the issue

**Comment by MohitGoyal09** [comment]
Yes I will work on it

**Comment by Hh440** [comment]
I will work on it

**Comment by TenzDelek** [comment]
> Yes I will work on it

will wait for @Hh440  till 12pm. if no response from his end, assigning the issue to @MohitGoyal09

**Comment by TenzDelek** [comment]
@Hh440  go ahead
