### ISSUE TITLE
Feat: Floalting Navbar with glass effect

### ISSUE THREAD

**Issue by AkashJana18** [TenzDelek/DearDiary#55]
### Is your proposal related to a problem?
Bored of seeing traditional navbar, which is not even sticky so to navigate we have scroll up to the top time and again which is irritating.

### Describe the solution you'd like
I would like to create floating navbar with glass effect which looks really cool and it will always be on the screen making accessing different pages a lot easier.

### Describe alternatives you've considered
Other solutions is  like making the navbar sticky for easy access.

### Additional context
Looks and feel of glass effect. Whether it be light or dark theme glassmorphism always looks super cool.
(Write your answer here.)

### Requirement/Document
This is the look and feel of floating glass navbar
![image](https://github.com/user-attachments/assets/ce56bd43-1b10-4e16-8318-c2db41760d54)

Please add gssoc-ext and level, hacktober tags and assign it to me as I am working on it.

**Comment by TenzDelek** [comment]
go ahead cc @AkashJana18

**Comment by AkashJana18** [comment]
how did the pr is closed?
Anyway I created new PR which has no conflict please merge it @TenzDelek
