### ISSUE TITLE
Feat: Customized scroll bar to improve UI/Ux

### ISSUE THREAD

**Issue by AkashJana18** [TenzDelek/DearDiary#56]
### Is your proposal related to a problem?
Scrollbar provided by the browser looks ugly.
(Write your answer here.)

### Describe the solution you'd like
I will make slim and sleek to give modern touch to the website

### Describe alternatives you've considered
Other solution can be to hide the scroll bar but it is not recommended

Please add gssoc24-ext, level , hacktober tag and assign me.

**Comment by TenzDelek** [comment]
we are planning to hide the scroll bar #33  so i dont think this issue is needed, you can work on the #33 if you want. 
the assign contributor seems inactive
