### ISSUE TITLE
Feat : supabase and prisma setup

### ISSUE THREAD

**Issue by TenzDelek** [TenzDelek/DearDiary#6]
set up supabase and prisma

**Comment by Abhi0049k** [comment]
Hi @TenzDelek, can you assign this issue to me?

**Comment by TenzDelek** [comment]
go ahead ! @Abhi0049k 
also do star the repo, it helps a ton in visibility

**Comment by Abhi0049k** [comment]
> go ahead ! @Abhi0049k also do star the repo, it helps a ton in visibility

okay

**Comment by Abhi0049k** [comment]
Hi @TenzDelek, I am a bit confused with supabase setup, can you guide me a little?

**Comment by TenzDelek** [comment]
drop the question here. i will answer when i am free

**Comment by Abhi0049k** [comment]
In some of my previous projects, I used Prisma, and for the database, I created one on Supabase and simply provided the Supabase database URL in the .env file.

**Comment by TenzDelek** [comment]
we are using prisma as the orm and the supabase as the storage.(no other supabase functionality is needed as for now)
refer this notion for setup guide
https://www.notion.so/Prisma-and-Supabase-10b5c2901d468084b67ce20af9d5edce?pvs=4

**Comment by Abhi0049k** [comment]
@TenzDelek please give the access
![image](https://github.com/user-attachments/assets/5f42d8e0-373c-41f3-b540-46b1687222c9)

**Comment by TenzDelek** [comment]
https://www.notion.so/Prisma-and-Supabase-10b5c2901d468084b67ce20af9d5edce?pvs=4
check again cc @Abhi0049k

**Comment by Abhi0049k** [comment]
> https://www.notion.so/Prisma-and-Supabase-10b5c2901d468084b67ce20af9d5edce?pvs=4 check again cc @Abhi0049k

@TenzDelek Still don't have the access
![image](https://github.com/user-attachments/assets/999cd710-d188-4ee4-a124-3cc3775bf275)
