### ISSUE TITLE
Feat : Creating a Diary page

### ISSUE THREAD

**Issue by TenzDelek** [TenzDelek/DearDiary#7]
create a page where we can write diary (crud) 
will discuss later about design and overview when assign is finish

**Comment by ananyakaligal** [comment]
could you please assign me this

**Comment by TenzDelek** [comment]
hey @ananyakaligal , thanks for the initiative but you are holding 3 pending issue, if you can finish one, I will assign this issue to you.

**Comment by Abhi0049k** [comment]
@TenzDelek can you assign me this issue?

**Comment by TenzDelek** [comment]
@Abhi0049k  go ahead

**Comment by Abhi0049k** [comment]
Hi @TenzDelek, regarding this diary page, can you tell me about the schema I will be working on?

**Comment by TenzDelek** [comment]
make it a simple, a diary schema having a body, and a title and link it with user (which we collect from clerk).

**Comment by Abhi0049k** [comment]
> make it a simple, a diary schema having a body, and a title and link it with user (which we collect from clerk).

okay, got it

**Comment by Sourabh782** [comment]
@TenzDelek is this issue open? I wanna contribute to it

**Comment by Abhi0049k** [comment]
> @TenzDelek is this issue open? I wanna contribute to it

I'm working on it
