### ISSUE TITLE
Fix: Getting 404 in login page route.

### ISSUE THREAD

**Issue by PrayanshParmar** [TenzDelek/DearDiary#73]
### Issue Summary

Getting 404 not found error in login page

### Steps to Reproduce

1. Went to home page
2. Click on sign up now button
![image](https://github.com/user-attachments/assets/5f2b8d9b-39fb-4c7d-942e-e634db1c1a5b)

3. Getting 404 not found
![image](https://github.com/user-attachments/assets/d65a9b3d-5c8a-4337-acf6-370cf50efdda)

### Actual Results

- When clicking on sign up button, 404 not found page appears.

### Expected Results

- When clicking on sign up button, clerk authentication screen must appear.

I want to fix this issue please let me assign this fix.

**Comment by TenzDelek** [comment]
thanks for the catch , go ahead @PrayanshParmar
