### ISSUE TITLE
Feat : Responsive Nav

### ISSUE THREAD

**Issue by TenzDelek** [TenzDelek/DearDiary#76]
as per title
make the nav responsive . a burger menu

**Comment by Sourabh782** [comment]
hello @TenzDelek may i work on it?

**Comment by DevyRuxpin** [comment]
Can I also work on this? @TenzDelek

**Comment by Sourabh782** [comment]
@DevyRuxpin it's nearly over

**Comment by DevyRuxpin** [comment]
Fair enough. Thanks anyways.

**Comment by Sourabh782** [comment]
@TenzDelek  can you check these?
![Screenshot 2024-10-10 080946](https://github.com/user-attachments/assets/1d642730-c65a-4a94-a6a4-fec5c30ba967)
![Screenshot 2024-10-10 080309](https://github.com/user-attachments/assets/0e811c44-586e-4804-baf1-c68fe0e4ee16)

**Comment by TenzDelek** [comment]
make the colour more dark #171717

**Comment by Sourabh782** [comment]
> make the colour more dark #171717

In top one right?

**Comment by Sourabh782** [comment]
![Screenshot 2024-10-10 090841](https://github.com/user-attachments/assets/bc516d52-2ac8-47da-aa98-5edd0b3941b4)
