### ISSUE TITLE
Feat : Smooth scroll using Lenis

### ISSUE THREAD

**Issue by TenzDelek** [TenzDelek/DearDiary#8]
use Lenis library to setup smooth scroll

**Comment by TenzDelek** [comment]
if any new contributor want to take this issue , I will guide you along. its easy to setup lenis

**Comment by lade6501** [comment]
I would like to work on it.

**Comment by Vivek7038** [comment]
can you assign these to me

**Comment by TenzDelek** [comment]
as @lade6501 is the first one to comment , assigning him to contribute. if he is not active for 2 days it will be pass to @Vivek7038

**Comment by lade6501** [comment]
I'm working on the issue.

**Comment by lade6501** [comment]
I only see 
`DearDiary: A Digital Note in this fast moving world`, am I missing something @TenzDelek ?

**Comment by TenzDelek** [comment]
the homepage is inprogress issue @lade6501

**Comment by lade6501** [comment]
So which page we are looking to add smooth scroll using Lenis?

**Comment by TenzDelek** [comment]
Yup, it's a simple implementation, install the Lenin package and at the page.jsx copy paste the code
