### ISSUE TITLE
no follow us at bottom of page

### ISSUE THREAD

**Issue by KapuluruBhuvaneswariVspdbct** [TenzDelek/DearDiary#80]
Found a bug? Please fill out the sections below. 👍

### Issue Summary
No follow us section at website

<img width="932" alt="image" src="https://github.com/user-attachments/assets/96c185ca-7051-4f90-b4ae-333b40418474">

### Steps to Reproduce

1.i will add  follow us sub section at bottom of page

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Actual Results

- What's happening right now that is different from what is expected

### Expected Results
the follow us page will increases chances of attraction

### Technical details

- Browser version, screen recording, console logs, network requests.
- Node.js version
- Anything else that you think could be an issue.

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
assign this to me

**Comment by TenzDelek** [comment]
follow us on what ? can we have a more context on this

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
Follow us icons of your links
