### ISSUE TITLE
add a mood tracker form to the website

### ISSUE THREAD

**Issue by KapuluruBhuvaneswariVspdbct** [TenzDelek/DearDiary#81]
Found a bug? Please fill out the sections below. 👍

### Issue Summary
Mood tracker form to a website 

### Steps to Reproduce

1. (for example) Went to ...
2. Clicked on...
3. ...

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Actual Results

it will know the diary website to track the mood
Mood tracker form to a website 
### Expected Results

- This is an ideal result that the system should get after the tests are performed

### Technical details

- Browser version, screen recording, console logs, network requests.
- Node.js version
- Anything else that you think could be an issue.

**Comment by TenzDelek** [comment]
currently not needed so closing this for now
