### ISSUE TITLE
Adding the footer

### ISSUE THREAD

**Issue by Bhanuprakash842** [TenzDelek/DearDiary#85]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

There is no proper footer in the home page . So I want to add a footer with all required info.Please assign me this issue under gssoc-ext,hacktoberfest-accepted

### Steps to Reproduce

1. Scroll the page to last

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Actual Results

![Screenshot 2024-10-09 220148](https://github.com/user-attachments/assets/100d2352-c61b-4bf7-8ce8-67ea54977ae2)

### Expected Results
I want to add the footer like as shown below with all required info.
This SS is just for a reference.

![Screenshot 2024-10-06 110000](https://github.com/user-attachments/assets/50a9d2b1-09ea-45f1-b1e2-0dd2da051db4)

### Technical details

- Browser version, screen recording, console logs, network requests.
- Node.js version
- Anything else that you think could be an issue.

**Comment by TenzDelek** [comment]
go ahead @Bhanuprakash842 
also do star the repo as well !!

**Comment by inkerton** [comment]
Can you assign this to me it has been 4 days?
@TenzDelek I would like to work on it

**Comment by TenzDelek** [comment]
Will wait till tomorrow

**Comment by inkerton** [comment]
@TenzDelek Is there any level2 /level3 issue I can work on today?

**Comment by Abhi0049k** [comment]
@TenzDelek, Can I work on this issue?

**Comment by inkerton** [comment]
> Will wait till tomorrow

Can you assign it to me today?

**Comment by TenzDelek** [comment]
Transfering the issue to @inkerton

**Comment by shamvrueth** [comment]
Can I work on this issue?

**Comment by inkerton** [comment]
Hey! I am sorry I was not well I made a PR please review it and let me know.

**Comment by inkerton** [comment]
Hey Please close the issue so I can get new Issues assigned
