### ISSUE TITLE
Adding Dark/Light Mode switch

### ISSUE THREAD

**Issue by divyalakshmi0** [TenzDelek/DearDiary#86]
- This feature allows users to switch between light and dark themes for better readability, reduced eye strain, and improved user experience based on personal preference or environmental conditions.

- Dark Mode: A theme with darker background colors and lighter text to reduce screen brightness and make it easier on the eyes, especially in low-light environments.
- Light Mode: A traditional theme with lighter backgrounds and darker text, suitable for well-lit environments.

**Comment by TenzDelek** [comment]
we had one pr for that and that doesnt work really well with the website. so currently not implementing this
