### ISSUE TITLE
Design : Logo Design for DearDiary

### ISSUE THREAD

**Issue by TenzDelek** [TenzDelek/DearDiary#9]
shoudn't be too fancy . subtle and clean 
give as per the ratio of a typical logo

**Comment by harshitpathak528** [comment]
Please assign to me I want to work on it.

**Comment by TenzDelek** [comment]
go ahead @harshitpathak528 
also do star the repo ! it helps in visibility

**Comment by harshitpathak528** [comment]
I raised the PR. Check it out
