### ISSUE TITLE
REQ: Making consistent theme across pages

### ISSUE THREAD

**Issue by TenzDelek** [TenzDelek/DearDiary#94]
currently the different route is having different theme making it inconsistent, 
for the theme follow the home page one  
background as #0A0A0A
and text #FAFAFA
boxes (div) #171717
<img width="1261" alt="image" src="https://github.com/user-attachments/assets/fffaea36-aeeb-4f4a-9590-2db175dac5eb">

# todo
change the theme for about and daily quote to above specify

**Comment by inkerton** [comment]
I can work on it can you assign it to me @TenzDelek

**Comment by inkerton** [comment]
Are you thinking of adding any Goal Setting or tracker???
