### ISSUE TITLE
Integrating Theme Toggler for Improved User experience

### ISSUE THREAD

**Issue by sezallagwal** [TenzDelek/DearDiary#98]
### Is your proposal related to a problem?

![image](https://github.com/user-attachments/assets/39b92b2c-86e3-4d61-a06f-aede450c16bd)
Rn your site don't have a theme toggler

### Describe the solution you'd like

I think it would be great to have a theme toggler so that users can switch between light and dark themes. It will give the site more professional look also It will help users with visual sensitivities or those who prefer light mode.

Proposed Solution:
-Add a toggle switch (maybe in the header or settings) to let users switch between light and dark themes.
-Store the user’s choice, so the site remembers their preference when they come back.
-Make sure everything on the site adjusts smoothly to the dark theme, with no issues in readability or functionality.

Please add gssoc-ext and level, hacktober tags and assign it to me.

**Comment by TenzDelek** [comment]
we once had the light mode toggle but it doesnt fit the theme. so we are not currently working on light mode
