### ISSUE TITLE
Signup button at the bottom still shows after logging in

### ISSUE THREAD

**Issue by sezallagwal** [TenzDelek/DearDiary#99]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

A summary of the issue. This needs to be a clear detailed-rich summary.

### Steps to Reproduce

1. After logging in, go to the home section
2. Navigate to the bottom
3. You will see a signup now button
![image](https://github.com/user-attachments/assets/e6d8121a-4a45-4de4-9b5d-a16f51306ea7)

The signup button should not be visible on the home page after successful login. Please assign it to me I can fix this @TenzDelek 
under- gssoc-ext and hacktoberfest

**Comment by TenzDelek** [comment]
go ahead
